sonar.projectKey=altair222000_react-redux-realworld-example
sonar.organization=altair222000


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=react-redux-realworld-example
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
